import "dotenv/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../generated/prisma/client";

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

type SourceSeed = {
  companyName: string;
  insuranceType: string;
  url: string;
  fetchType: string;
  active: boolean;
  fetchIntervalMin?: number;
  note?: string;
};

const sources: SourceSeed[] = [
  // ── 生保 10社 ──
  {
    companyName: "日本生命",
    insuranceType: "life",
    url: "https://www.nissay.co.jp/kaisha/news/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "第一生命",
    insuranceType: "life",
    url: "https://www.dai-ichi-life.co.jp/company/news/index.html",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "明治安田生命",
    insuranceType: "life",
    url: "https://www.meijiyasuda.co.jp/profile/news/release/index.html",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "住友生命",
    insuranceType: "life",
    url: "https://www.sumitomolife.co.jp/news/newsrelease/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "かんぽ生命",
    insuranceType: "life",
    url: "https://www.jp-life.japanpost.jp/information/press/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "アフラック生命",
    insuranceType: "life",
    url: "https://www.aflac.co.jp/corp/profile/news/",
    fetchType: "html",
    active: false,
    note: "WebFetchで403 Forbidden。bot対策の可能性。将来Puppeteer対応時にactive=1へ",
  },
  {
    companyName: "プルデンシャル生命",
    insuranceType: "life",
    url: "https://www.prudential.co.jp/press/",
    fetchType: "html",
    active: false,
    note: "WebFetchで403 Forbidden。bot対策の可能性。将来Puppeteer対応時にactive=1へ",
  },
  {
    companyName: "マニュライフ生命",
    insuranceType: "life",
    url: "https://www.manulife.co.jp/ja/individual/about/newsrelease/press.html",
    fetchType: "html",
    active: false,
    note: "WebFetchで403 Forbidden。bot対策の可能性。将来Puppeteer対応時にactive=1へ",
  },
  {
    companyName: "ソニー生命",
    insuranceType: "life",
    url: "https://www.sonylife.co.jp/company/news/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "ライフネット生命",
    insuranceType: "life",
    url: "https://www.lifenet-seimei.co.jp/newsrelease/",
    fetchType: "html",
    active: true,
  },

  // ── 損保 10社(東京海上日動火災は自社ページ+HD RSSの2レコード) ──
  {
    companyName: "東京海上日動火災",
    insuranceType: "nonlife",
    url: "https://www.tokiomarine-nichido.co.jp/company/release/",
    fetchType: "html",
    active: false,
    note: "自社ページはWebFetchで403 Forbidden。実収集は東京海上HDのRSSソースを使用。将来Puppeteer対応時にactive=1へ",
  },
  {
    companyName: "東京海上日動火災",
    insuranceType: "nonlife",
    url: "https://www.tokiomarinehd.com/feed/release.xml",
    fetchType: "rss",
    active: true,
    note: "自社ページ403の代替として東京海上HDのプレスリリースRSSを登録",
  },
  {
    companyName: "損害保険ジャパン",
    insuranceType: "nonlife",
    url: "https://www.sompo-japan.co.jp/news/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "三井住友海上火災",
    insuranceType: "nonlife",
    url: "https://www.ms-ins.com/news/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "あいおいニッセイ同和損保",
    insuranceType: "nonlife",
    url: "https://www.aioinissaydowa.co.jp/corporate/about/news/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "AIG損保",
    insuranceType: "nonlife",
    url: "https://www.aig.co.jp/sonpo/company/news",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "SBI損保",
    insuranceType: "nonlife",
    url: "https://www.sbisonpo.co.jp/company/news/",
    fetchType: "html",
    active: true,
  },
  {
    companyName: "ソニー損保",
    insuranceType: "nonlife",
    url: "https://from.sonysonpo.co.jp/topics/news/",
    fetchType: "html",
    active: false,
    note: "一覧ページがWebFetchで403 Forbidden。将来Puppeteer対応時にactive=1へ",
  },
  {
    companyName: "東京海上ダイレクト",
    insuranceType: "nonlife",
    url: "https://www.e-design.net/company/information/",
    fetchType: "html",
    active: true,
    note: "2025年10月にイーデザイン損保より社名変更。旧URLは登録せず新ブランド名のみ",
  },
  {
    companyName: "SOMPOダイレクト損害保険",
    insuranceType: "nonlife",
    url: "https://news-ins-saison.dga.jp/topics/",
    fetchType: "html",
    active: true,
    note: "2024年10月にセゾン自動車火災保険より社名変更。旧URLは登録せず新ブランド名のみ",
  },
  {
    companyName: "楽天損保",
    insuranceType: "nonlife",
    url: "https://www.rakuten-sonpo.co.jp/news/",
    fetchType: "html",
    active: true,
  },

  // ── Statuspage対象 15件(SaaS各社のステータスページJSON) ──
  {
    companyName: "Slack",
    insuranceType: "statuspage",
    url: "https://slack-status.com/api/v2.0.0/current",
    fetchType: "json",
    active: true,
    note: "旧/api/v2/summary.jsonは404(現行APIに移行済み)",
  },
  {
    companyName: "Notion",
    insuranceType: "statuspage",
    url: "https://www.notion-status.com/api/v2/summary.json",
    fetchType: "json",
    active: true,
  },
  {
    companyName: "Zoom",
    insuranceType: "statuspage",
    url: "https://status.zoom.us/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "GitHub",
    insuranceType: "statuspage",
    url: "https://www.githubstatus.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Cloudflare",
    insuranceType: "statuspage",
    url: "https://www.cloudflarestatus.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Stripe",
    insuranceType: "statuspage",
    url: "https://status.stripe.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "実体はwww.stripestatus.com(Statuspage.io)。そちらもrobots.txtが/apiをDisallowしているため取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Datadog",
    insuranceType: "statuspage",
    url: "https://status.datadoghq.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Zendesk",
    insuranceType: "statuspage",
    url: "https://status.zendesk.com/api/incidents/active",
    fetchType: "json",
    active: true,
    note: "旧/api/v2/summary.jsonは404。公式Status API(developer.zendesk.com記載)に変更",
  },
  {
    companyName: "HubSpot",
    insuranceType: "statuspage",
    url: "https://status.hubspot.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Twilio",
    insuranceType: "statuspage",
    url: "https://status.twilio.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Asana",
    insuranceType: "statuspage",
    url: "https://status.asana.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Atlassian",
    insuranceType: "statuspage",
    url: "https://status.atlassian.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Dropbox",
    insuranceType: "statuspage",
    url: "https://status.dropbox.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Figma",
    insuranceType: "statuspage",
    url: "https://status.figma.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "Statuspage.io標準robots.txtが/apiをDisallowしているため、/api/v2/summary.jsonを取得不可。robots.txt尊重ポリシーによりinactiveとする",
  },
  {
    companyName: "Salesforce",
    insuranceType: "statuspage",
    url: "https://status.salesforce.com/api/v2/summary.json",
    fetchType: "json",
    active: false,
    note: "summary.jsonへの直接アクセスがサーバー側で拒否される(HTTP 403 'Direct API access not allowed')。robots.txtではなくAPI自体の制約",
  },

  // ── C: SaaS障害 追加ソース(サイボウズ/freee/SmartHR/MoneyForward/Chatwork) ──
  {
    companyName: "サイボウズ kintone",
    insuranceType: "statuspage",
    url: "https://cs.cybozu.co.jp/information/trouble/product_cloud/kintone/rss.xml",
    fetchType: "rss",
    active: true,
  },
  {
    companyName: "サイボウズ Office",
    insuranceType: "statuspage",
    url: "https://cs.cybozu.co.jp/information/trouble/product_cloud/ofcloud/rss.xml",
    fetchType: "rss",
    active: true,
  },
  {
    companyName: "サイボウズ Garoon",
    insuranceType: "statuspage",
    url: "https://cs.cybozu.co.jp/information/trouble/product_cloud/grcloud/rss.xml",
    fetchType: "rss",
    active: true,
    note: "現行3テーマの直接対象ではないが同一ドメインのため登録。優先度低",
  },
  {
    companyName: "サイボウズ メールワイズ",
    insuranceType: "statuspage",
    url: "https://cs.cybozu.co.jp/information/trouble/product_cloud/mailwisecom/rss.xml",
    fetchType: "rss",
    active: true,
    note: "現行3テーマの直接対象ではないが同一ドメインのため登録。優先度低",
  },
  {
    companyName: "cybozu.com",
    insuranceType: "statuspage",
    url: "https://status.cybozu.com/status/",
    fetchType: "html",
    active: false,
    note: "robots.txtは/status/(完全一致)のみAllowで配下は禁止。当該ページはJSでクライアント側描画するSPAシェルで静的HTMLは291byte固定(障害発生時も変化しない)。html差分検知が機能しないためPuppeteer対応時にactive=1へ",
  },
  {
    companyName: "freee",
    insuranceType: "statuspage",
    url: "https://status.freee.co.jp/?locale=ja",
    fetchType: "html",
    active: true,
    note: "Hund.io系ステータスページ(Statuspage.ioではない)。robots.txtに/api等のDisallow無く、実際のステータス本文がサーバー側HTMLに含まれることを確認済み",
  },
  {
    companyName: "SmartHR",
    insuranceType: "statuspage",
    url: "https://support.smarthr.jp/ja/info/status/page/1/",
    fetchType: "html",
    active: false,
    note: "静的HTMLは「お知らせ情報の取得中」のプレースホルダのみで、__NEXT_DATA__のpagePropsにも記事本体を含まずクライアント側取得。Puppeteer未対応のため見送り",
  },
  {
    companyName: "マネーフォワード ME",
    insuranceType: "statuspage",
    url: "https://support.me.moneyforward.com/hc/ja/sections/4407400737177-メンテナンス・障害・不具合情報",
    fetchType: "html",
    active: false,
    note: "WebFetchで403 Forbidden(Cloudflareのbot対策「Just a moment...」)。将来Puppeteer対応時にactive=1へ",
  },
  {
    companyName: "マネーフォワード biz",
    insuranceType: "statuspage",
    url: "https://support.bfm.x.moneyforward.com/hc/ja/sections/10876583717017-障害・メンテナンス",
    fetchType: "html",
    active: false,
    note: "WebFetchで403 Forbidden(Cloudflareのbot対策「Just a moment...」)。将来Puppeteer対応時にactive=1へ",
  },
  {
    companyName: "Chatwork",
    insuranceType: "statuspage",
    url: "https://help.chatwork.com/hc/ja/sections/201963352-メンテナンス・障害・その他",
    fetchType: "html",
    active: false,
    note: "WebFetchで403 Forbidden(Cloudflareのbot対策「Just a moment...」)。将来Puppeteer対応時にactive=1へ",
  },

  // ── テーマF: 海外SaaS changelog/pricing 調査分(2026-07-17調査、2026-07-18登録) ──
  {
    companyName: "Slack changelog",
    insuranceType: "theme_f",
    url: "https://slack.com/whats-new",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1440,
  },
  {
    companyName: "Slack pricing",
    insuranceType: "theme_f",
    url: "https://slack.com/pricing",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4320,
  },
  {
    companyName: "Notion changelog",
    insuranceType: "theme_f",
    url: "https://notion.com/releases",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1453,
  },
  {
    companyName: "Notion pricing",
    insuranceType: "theme_f",
    url: "https://notion.com/pricing",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4333,
  },
  {
    companyName: "Figma changelog",
    insuranceType: "theme_f",
    url: "https://www.figma.com/release-notes/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1466,
    note: "ページ内にRSS購読ボタンあり(具体的feed URL未確定)。将来HTML→RSS切替を検討",
  },
  {
    companyName: "Figma pricing",
    insuranceType: "theme_f",
    url: "https://www.figma.com/pricing/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4346,
  },
  {
    companyName: "Linear changelog",
    insuranceType: "theme_f",
    url: "https://linear.app/changelog",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1479,
  },
  {
    companyName: "Linear pricing",
    insuranceType: "theme_f",
    url: "https://linear.app/pricing",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4359,
  },
  {
    companyName: "Airtable changelog",
    insuranceType: "theme_f",
    url: "https://airtable.com/whatsnew",
    fetchType: "html",
    active: false,
    note: "素のGETで本文がほぼ空(JS SPA)。Puppeteer未対応のため見送り",
  },
  {
    companyName: "Airtable pricing",
    insuranceType: "theme_f",
    url: "https://airtable.com/pricing",
    fetchType: "html",
    active: false,
    note: "価格表がJSで描画されHTMLに乗らない。Puppeteer未対応のため見送り",
  },
  {
    companyName: "Miro changelog",
    insuranceType: "theme_f",
    url: "https://miro.com/changelog/",
    fetchType: "html",
    active: false,
    note: "robots.txtが`Disallow: /changelog/`を明示。robots.txt尊重ポリシーによりinactive",
  },
  {
    companyName: "Miro pricing",
    insuranceType: "theme_f",
    url: "https://miro.com/pricing/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4372,
    note: "`/pricing/`単体のみ許可(`/pricing/pro/`等サブパスはrobots.txtでDisallow)。対象URLは末尾スラッシュ必須",
  },
  {
    companyName: "Zoom pricing",
    insuranceType: "theme_f",
    url: "https://zoom.us/pricing",
    fetchType: "html",
    active: false,
    note: "プラン名はSSRだが価格数値がJS注入で取得不可。Puppeteer未対応のため見送り",
  },
  {
    companyName: "Atlassian changelog",
    insuranceType: "theme_f",
    url: "https://www.atlassian.com/software/jira/whats-new/cloud",
    fetchType: "html",
    active: false,
    note: "素のGETで本文がほぼ空(JS SPA)。Puppeteer未対応のため見送り",
  },
  {
    companyName: "Asana pricing",
    insuranceType: "theme_f",
    url: "https://asana.com/pricing",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4385,
  },
  {
    companyName: "HubSpot pricing",
    insuranceType: "theme_f",
    url: "https://www.hubspot.com/pricing",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4398,
  },
  {
    companyName: "Salesforce pricing",
    insuranceType: "theme_f",
    url: "https://www.salesforce.com/pricing/",
    fetchType: "html",
    active: false,
    note: "WebFetchで403 Forbiddenを2回再現(robots.txt自体も403で未確認)。bot対策の可能性",
  },
  {
    companyName: "Zendesk pricing",
    insuranceType: "theme_f",
    url: "https://www.zendesk.com/pricing/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4411,
    note: "アクセス元によりzendesk.co.jp/pricingへ302転送される場合あり。挙動変化に注意",
  },
  {
    companyName: "Canva changelog",
    insuranceType: "theme_f",
    url: "https://www.canva.com/launches/",
    fetchType: "html",
    active: false,
    note: "素のGETで本文が空(JS SPA)。またrobots.txtがGPTBot/ClaudeBot/CCBot/anthropic-aiを名指しでDisallowしている(User-agent:*には制限なし)",
  },
  {
    companyName: "Canva pricing",
    insuranceType: "theme_f",
    url: "https://www.canva.com/en/pricing/",
    fetchType: "html",
    active: false,
    note: "UA判定で「非対応ブラウザ」案内ページが返り実価格取得不可。robots.txtの名指しDisallowも参照",
  },
  {
    companyName: "GitHub changelog",
    insuranceType: "theme_f",
    url: "https://github.blog/changelog/feed/",
    fetchType: "rss",
    active: true,
    fetchIntervalMin: 1492,
    note: "HTML版(github.blog/changelog/)ではなく公式RSSフィードを採用",
  },
  {
    companyName: "GitHub pricing",
    insuranceType: "theme_f",
    url: "https://github.com/pricing",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4424,
  },
  {
    companyName: "Stripe pricing",
    insuranceType: "theme_f",
    url: "https://stripe.com/pricing",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 4437,
  },

  // ── テーマG: パブコメ・審議会/検討会・報道発表 調査分(2026-07-17〜18調査・登録) ──
  {
    companyName: "e-Govパブコメ 意見募集中",
    insuranceType: "theme_g",
    url: "https://public-comment.e-gov.go.jp/rss/pcm_list.xml",
    fetchType: "rss",
    active: true,
    fetchIntervalMin: 1440,
    note: "robots.txtは404(制限なし)。本番UAで200・正常RSS(RDF)を確認済み。HTML一覧(/pcm/list)よりRSSを優先",
  },
  {
    companyName: "e-Govパブコメ 結果公示",
    insuranceType: "theme_g",
    url: "https://public-comment.e-gov.go.jp/rss/pcm_result.xml",
    fetchType: "rss",
    active: true,
    fetchIntervalMin: 1451,
    note: "募集開始とは別建てのRSS。提出意見への省庁回答を含む結果公示専用フィード",
  },
  {
    companyName: "金融庁 審議会・検討会",
    insuranceType: "theme_g",
    url: "https://www.fsa.go.jp/singi/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1440,
  },
  {
    companyName: "金融庁 報道発表資料",
    insuranceType: "theme_g",
    url: "https://www.fsa.go.jp/news/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1451,
  },
  {
    companyName: "総務省 審議会・委員会・会議等",
    insuranceType: "theme_g",
    url: "https://www.soumu.go.jp/menu_sosiki/singi/index.html",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1462,
    note: "非UTF-8(Shift_JIS系と推定)エンコーディング。パーサー実装時に文字コード変換対応が必要",
  },
  {
    companyName: "総務省 報道資料一覧",
    insuranceType: "theme_g",
    url: "https://www.soumu.go.jp/menu_news/s-news/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1473,
    note: "総務省審議会ページと同様エンコーディング要確認",
  },
  {
    companyName: "厚生労働省 審議会・研究会等",
    insuranceType: "theme_g",
    url: "https://www.mhlw.go.jp/stf/shingi/indexshingi.html",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1484,
  },
  {
    companyName: "厚生労働省 報道発表資料",
    insuranceType: "theme_g",
    url: "https://www.mhlw.go.jp/stf/houdou/index.html",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1495,
  },
  {
    companyName: "国土交通省 報道発表資料",
    insuranceType: "theme_g",
    url: "https://www.mlit.go.jp/pressrelease.html",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1506,
    note: "国交省はrobots.txt自体が404(ファイル不存在、制限なしとして扱う)",
  },
  {
    companyName: "環境省 審議会・検討会",
    insuranceType: "theme_g",
    url: "https://www.env.go.jp/council/o_info.html",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1462,
    note: "当初調査対象だった/council/はナビゲーション型で日付なしのため、実データのある子ページに差し替え",
  },
  {
    companyName: "環境省 報道発表資料",
    insuranceType: "theme_g",
    url: "https://www.env.go.jp/press/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1517,
  },
  {
    companyName: "デジタル庁 審議会等",
    insuranceType: "theme_g",
    url: "https://www.digital.go.jp/councils",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1528,
    note: "サイト全体共通RSS(https://www.digital.go.jp/rss/news.xml)ありだが本ページ専用ではないためHTML採用",
  },
  {
    companyName: "デジタル庁 news",
    insuranceType: "theme_g",
    url: "https://www.digital.go.jp/news?category=144",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1539,
  },
  {
    companyName: "個人情報保護委員会 報道発表",
    insuranceType: "theme_g",
    url: "https://www.ppc.go.jp/news/press/",
    fetchType: "html",
    active: true,
    fetchIntervalMin: 1550,
  },
  {
    companyName: "経済産業省 審議会・研究会",
    insuranceType: "theme_g",
    url: "https://www.meti.go.jp/shingikai/",
    fetchType: "html",
    active: false,
    note: "robots.txt自体が403、本番UA(politeFetch)での実地fetchも403継続。WAF拒否と判断しinactive",
  },
  {
    companyName: "経済産業省 報道発表",
    insuranceType: "theme_g",
    url: "https://www.meti.go.jp/press/",
    fetchType: "html",
    active: false,
    note: "robots.txt自体が403、本番UA(politeFetch)での実地fetchも403継続。WAF拒否と判断しinactive",
  },

  // ── テーマH: ビジネスヒントのメタ・ハーヴェスト 調査分(2026-07-18調査・登録) ──
  {
    companyName: "Hacker News Show HN",
    insuranceType: "theme_h",
    url: "https://hacker-news.firebaseio.com/v0/showstories.json",
    fetchType: "json",
    active: true,
    fetchIntervalMin: 1440,
    note: "公式Firebase API。robots.txt許可、規約上の商用制限記載なし、明示レート制限なし",
  },
  {
    companyName: "Hacker News Ask HN",
    insuranceType: "theme_h",
    url: "https://hacker-news.firebaseio.com/v0/askstories.json",
    fetchType: "json",
    active: true,
    fetchIntervalMin: 1451,
    note: "公式Firebase API。robots.txt許可、規約上の商用制限記載なし、明示レート制限なし",
  },
  {
    companyName: "Product Hunt フィード",
    insuranceType: "theme_h",
    url: "https://www.producthunt.com/feed",
    fetchType: "rss",
    active: true,
    fetchIntervalMin: 1462,
    note: "公式Atomフィード。GraphQL API(v2)は規約上商用利用不可(要問合せ)のため見送り、フィードで代替",
  },
  {
    companyName: "はてなブックマーク テクノロジー",
    insuranceType: "theme_h",
    url: "https://b.hatena.ne.jp/hotentry/it.rss",
    fetchType: "rss",
    active: true,
    fetchIntervalMin: 1473,
  },
  {
    companyName: "はてなブックマーク 世の中",
    insuranceType: "theme_h",
    url: "https://b.hatena.ne.jp/hotentry/social.rss",
    fetchType: "rss",
    active: true,
    fetchIntervalMin: 1484,
  },
];

async function main() {
  await prisma.source.deleteMany();
  await prisma.source.createMany({ data: sources });

  const total = await prisma.source.count();
  const activeCount = await prisma.source.count({ where: { active: true } });
  console.log(`sources投入完了: 全${total}件 / active=${activeCount}件 / inactive=${total - activeCount}件`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
